function customFigure(resolution,backgroundcolor)
%% 关闭MATLAB Figure的各种工具栏，指定窗口分辨率和背景色
figure('MenuBar', 'none', ...
    'ToolBar', 'none', ...
    'NumberTitle', 'off', ...
    'Name', '', ...
    'Units', 'pixels', ...
    'Position',resolution,'color',backgroundcolor)
end